name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - name: Cache 
        uses: actions/cache@v2
        env:
          armsdk-cache-version: 21.07
        with:
          path: ./armsdk
          key: armsdk-cache-${{ env.armsdk-cache-version }}
      - name: Install blender
        run: sudo snap install blender --classic
      - name: Install armory
        run: |
          if [ -d "armsdk" ]; then; git clone https://github.com/armory3d/armsdk.git --recurse-submodules; fi
          blender -noaudio -b -P blender/enable_addon.py
      - name: Install haxelibs
        run: |
          haxelib install markdown
      - name: Get armory_examples
        uses: actions/checkout@v2
        with:
          repository: tong/armory_examples
          path: armory_examples
          ref: examples-browser-compat
      - name: Get armory_templates
        uses: actions/checkout@v2
        with:
          repository: tong/armory_templates
          path: armory_templates
          ref: examples-browser-compat
      - name: Get armory_tutorials
        uses: actions/checkout@v2
        with:
          repository: tong/armory_tutorials
          path: armory_tutorials
          ref: examples-browser-compat
      - name: Build armory_examples
        run: haxe build-examples.hxml
      - name: Build armory_templates
        run: haxe build-templates.hxml
      - name: Build armory_tutorials
        run: haxe build-tutorials.hxml
      - name: Build application
        run: |
          ls web/examples
          ls web/templates
          ls web/tutorials
          haxe app.hxml
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: web
