name: CI

on:
  push:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - name: Install blender
        run: sudo snap install blender --classic
      - name: Install armsdk
        run: |
          git clone --recurse-submodules https://github.com/armory3d/armsdk.git
          blender -noaudio -b -P blender/enable_addon.py
      - name: Build examples
        run: haxe build-examples.hxml 
      - name: Build templates
        run: haxe build-templates.hxml 
      - name: Build tutorials
        run: haxe build-tutorials.hxml 
      - name: Build application
        run: |
          haxelib install markdown --always
          haxe app.hxml 
